# Step 1: Build the React app
FROM node:16 AS build

WORKDIR /app

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Step 2: Serve the React app using nginx
FROM nginx:stable-otel
# ENV OTEL_SERVICE_NAME="demo-react-app"
# ENV OTEL_EXPORTER_OTLP_ENDPOINT="http://localhost:4317"
# ENV OTEL_TRACES_EXPORTER="otlp"
# ENV OTEL_METRICS_EXPORTER="otlp"
# ENV OTEL_LOGS_EXPORTER="otlp"

COPY --from=build /app/build /usr/share/nginx/html

COPY conf/nginx.conf.template /etc/nginx/nginx.conf.template
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 80

ENTRYPOINT ["/entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]