# Step 1: Build the React app
FROM node:16 AS build

WORKDIR /app

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Step 2: Serve the React app using nginx
FROM nginx:1.25.3

COPY --from=build /app/build /usr/share/nginx/html

COPY conf/nginx.conf.template /etc/nginx/nginx.conf.template
COPY conf/default.conf.template /etc/nginx/conf.d/default.conf
COPY conf/opentelemetry_agent.conf.template /etc/nginx/conf.d/opentelemetry_agent.conf.template

RUN echo "load_module /opt/opentelemetry-webserver/agent/WebServerModule/Nginx/1.25.3/ngx_http_opentelemetry_module.so;\n$(cat /etc/nginx/nginx.conf.template)" > /etc/nginx/nginx.conf.template
COPY entrypoint_otelinst.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 80

ENTRYPOINT ["/entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]